### ISSUE TITLE
What kind of architecture is used in this project?

### ISSUE THREAD

**Issue by NikasZalias** [cloudacademy/fraud-detection#3]
Wanted to ask what kind of architecture is used in this project? DNN, RNN or what? how many hidden layers are here? how many neurons are used to create this neural network?

**Comment by alexcasalboni** [comment]
Hey @NikasZalias, check out the training script [here](https://github.com/cloudacademy/fraud-detection/blob/master/src/train.py#L5).

It's not a neural network at all, just a plain old linear model :)

We used [scikit-learn](https://scikit-learn.org) and [Logistic Regression](https://en.wikipedia.org/wiki/Logistic_regression), plus [grid search](https://en.wikipedia.org/wiki/Hyperparameter_optimization#Grid_search) to optimize hyperparameters.
