### ISSUE TITLE
Dataset link is broken .

### ISSUE THREAD

**Issue by faisaltadavi23** [cloudacademy/fraud-detection#4]
The link provided for dataset (https://clouda-datasets.s3.amazonaws.com/creditcard.csv.zip) is not working . Please if you have it on device do share the dataset. Thank you !

**Comment by stefanocascavilla** [comment]
Hello Faisal, this is Stefano from Cloud Academy.
I'm glad to inform you the issue has just been fixed, and that you're now able to download the CSV dataset.

**Comment by faisaltadavi23** [comment]
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>clouda-datasets</BucketName>
<RequestId>GYR6KEA5FEJYSE7K</RequestId>
<HostId>X+YpkTDaL/e+A0FVqmxC+1SHkTmXlJyZRU3JuEeHMbNfPBEHKExCAoRIXqJ8DtcoULPNepPee3w=</HostId>
</Error>


This is what I get when I click on the link. It's still happening .

**Comment by stefanocascavilla** [comment]
Hello Faisal, the link to download the CSV has been fixed. The following one (https://clouda-datasets.s3.amazonaws.com/creditcard.csv.zip) doesn't work and it's not linked in the README.md anymore. You now need to use the new one (https://clouda-labs-assets.s3-us-west-2.amazonaws.com/fraud-detection/creditcard.csv.zip)

**Comment by faisaltadavi23** [comment]
Thank you so much Stefano !
